# Used to test various versions
FROM rocker/tidyverse:RVERSION

RUN apt-get update && apt-get install -y \
      make \
      qpdf \
    && rm -rf /var/apt/cache/*

WORKDIR /root
COPY . ./loggit
WORKDIR /root/loggit

CMD ["Rscript", "-e", "devtools::check()"]
